FORMAT: X-1A

# The Simplest API

# GET /post{/id}
+ Parameters

    + id ... Id of a post.

+ Response 200 (application/json)
    
        {
            "title: "Hello World !",
            "content: "Hello !"
        }