FORMAT: X-1A

# Jobs API
Welcome to the our Jobs API documentation.

# Group Job Offer

The following is a section of resources related to the job offers

## Job offer [/job/{webid}|{graphid}]
Get Job Offer informations using either a GraphID or a webID

### Get a Job offer [GET]

+ Parameters

  + id (required, graphid, `0023ac3vf970lf7p`) ... Id of a job.

+ Response 200 (application/json)

        {
            "type": "MOBILE JOB",
            "updated_time" : "2013-09-24T10:23:38+0200
        }

+ Response 400 (application/json)

        {
        }

## Apply to a job offer [/user/{webid}|{graphid}/apply/job/{webid}|{graphid}]
Apply to a job offer

### Apply to a job offer [POST]

+ Request (application/json)

        {
            "message": "message of my application"
        }

+ Response 201 (application/json)

        {
            "status": "created"
        }















